### PR TITLE
Flake8 the code.

### PR DESCRIPTION
**Pull request by icemac**
Ported Flake8ing of the code from #6 but this time without using `black`. I did the fixes by hand.

### CODE REVIEW

**Comment by icemac** [comment]
The coverage decreased because I deleted some useless but covered lines in the test files.

**Review by jamadden — APPROVED** [review]
I see nothing wrong with it.

**Review by mgedmin — APPROVED** [review]
LGTM!

**Comment by icemac** [comment]
Thank you for reviewing.

**Pull request merged**
