### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by icemac**
I am going to break #6 into smaller pieces: First step is fixing the tests.

### CODE REVIEW

**Comment by icemac** [comment]
I created #8 for further investigation what is the problem with `beautifulsoup4 >= 4.7`.

**Review by ale-rt — APPROVED** [review]
Looks good to me even if I do not see who is pulling in BS4 and I have no chance to better check this now.

**Review by mgedmin — APPROVED** [review]
Eh, lgtm.

(I'm not a fan of `<` requirements.)

**Comment by mgedmin** [comment]
I've a fix in zope.testbrowser: https://github.com/zopefoundation/zope.testbrowser/pull/63.  Once it's merged and released, we can drop the `<` constraint.

**Pull request merged**
