### PR TITLE
Config with pure python

### PR DESCRIPTION
**Pull request by icemac**
* Fix tests for PyPy3.
* Add support for Python 3.9 and 3.10.

**Caution:** Does not build locally on my MacOS machine because C99 compiler fails to compile `zopyx.txng3.ext`.

### CODE REVIEW

**Comment by icemac** [comment]
PyPy3 crashes the interpreter and Python 3.10 seems to fail with https://github.com/zopefoundation/zope.index/issues/30.

**Comment by icemac** [comment]
The new zope.index release fixes the Python 3.10 tests. For PyPy3 still the interpreter crashes.

**Comment by icemac** [comment]
Switching PyPy3 from 3.6 to 3.7 did not help, it still crashes the interpreter.

**Comment by icemac** [comment]
Wow, using PyPy3.8 helps.

**Review by dataflake — APPROVED** [review]
PyPy support in Zope Foundation packages seems random, there's never been any effort to push that. So whenever I see PyPy support in a package I wonder how important that really is.

**Comment by icemac** [comment]
Trying to remove PyPy support somewhere results in replies claiming it to be important, so I am doing my best to keep the status quo.

Thank you for reviewing this PR. 😃

**Pull request merged**
