### PR TITLE
Config with pure python template

### PR DESCRIPTION
**Pull request by icemac**
Locally on MacOS all Python versions fail to compile `zopyx.txng3.ext`.

Run using https://github.com/zopefoundation/meta/pull/190.

### CODE REVIEW

**Comment by icemac** [comment]
In PyPy3 the interpreter crashes during the tests.

**Comment by dataflake** [comment]
`isort` is not identifying `pytz` as a third-party package. Something like this in `.meta.toml` may fix it:

```
[isort]
known_third_party = "pytz"
```

**Comment by icemac** [comment]
As running the tests on PyPy-3.9 fixes the tests we should default to that PyPy version in `meta/config`.

**Comment by dataflake** [comment]
> As running the tests on PyPy-3.9 fixes the tests we should default to that PyPy version in `meta/config`.

I agree

**Review by dataflake — APPROVED** [review]

**Comment by icemac** [comment]
Thank you for reviewing this PR. 😃

**Pull request merged**
